apiVersion: batch/v1
kind: Job
metadata:
  name: np-untrusted-client
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: np-untrusted-client
    spec:
      restartPolicy: Never
      containers:
        - name: app
          image: alpine
          command:
            - wget
            - http://np-service
